apps/accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from apps.accounts import views

app_name = 'accounts'

urlpatterns = [
    path('login', views.MyLoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('signup', views.MySignupView.as_view(), name='signup'),
]

apps/vacancies/urls.py
from django.urls import path, re_path

from apps.vacancies.views import public, mycompany, myvacanciesview

app_name = 'vacancies'

urlpatterns = [
    path('', public.IndexView.as_view(), name='index'),
    path('vacancies/', public.VacanciesView.as_view(), name='vacancies'),
    path('vacancies/cat/<slug:specialty>',
         public.VacanciesBySpecialtyView.as_view(),
         name='vacancies_by_specialty'
         ),
    path('companies/<int:pk>', public.CompanyView.as_view(), name='company'),
    path('vacancies/<int:pk>', public.VacancyView.as_view(), name='vacancy'),
    path('vacancies/appsuccess', public.ApplicationSuccessView.as_view(), name='app_success'),

    path('mycompany/letsstart/', mycompany.MyCompanyLetsStart.as_view(), name='my_company_lets_start'),
    path('mycompany/create/', mycompany.MyCompanyCreateView.as_view(), name='my_company_create'),
    path('mycompany/', mycompany.MyCompanyEditView.as_view(), name='my_company'),

    path('mycompany/vacancies/', myvacanciesview.MyVacanciesView.as_view(), name='my_vacancies'),
    path('mycompany/vacancies/create/', myvacanciesview.MyVacancyCreateView.as_view(), name='my_vacancy_create'),
    path('mycompany/vacancies/<int:pk>', myvacanciesview.MyVacancyEditView.as_view(), name='my_vacancy_edit'),
]

vacavaca/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from apps.vacancies.views import public

app_name = 'vacavaca'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.vacancies.urls')),
    path('', include('apps.accounts.urls')),
]

handler404 = public.custom_handler404
handler500 = public.custom_handler500

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

apps/vacancies/models.py
from datetime import date

from django.contrib.auth.models import User
from django.db import models

from phonenumber_field.modelfields import PhoneNumberField

from vacavaca.settings import MEDIA_COMPANY_IMAGE_DIR, MEDIA_SPECIALTY_IMAGE_DIR, DEFAULT_COMPANY_IMAGE, \
    DEFAULT_SPECIALTY_IMAGE


class Company(models.Model):
    name = models.CharField(max_length=128, verbose_name='Название компаниии')
    location = models.CharField(max_length=48, verbose_name='География')
    logo = models.ImageField(upload_to=MEDIA_COMPANY_IMAGE_DIR, default=DEFAULT_COMPANY_IMAGE, verbose_name='Логотип')
    description = models.TextField(verbose_name='Информация о компании')
    employee_count = models.IntegerField(verbose_name='Количество человек в компании')
    owner = models.OneToOneField(User, on_delete=models.SET_NULL, related_name='company', null=True, blank=True)


class Specialty(models.Model):
    code = models.CharField(max_length=128)
    title = models.CharField(max_length=128)
    picture = models.ImageField(upload_to=MEDIA_SPECIALTY_IMAGE_DIR, default=DEFAULT_SPECIALTY_IMAGE)

    def __str__(self):
        return self.title


class Vacancy(models.Model):
    title = models.CharField(max_length=128, verbose_name='Название вакансии')
    specialty = models.ForeignKey(
        Specialty, on_delete=models.PROTECT, related_name='vacancies', verbose_name='Специализация'
    )
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='vacancies')
    skills = models.CharField(max_length=256, verbose_name='Требуемые навыки')
    description = models.TextField(verbose_name='Описание вакансии')
    salary_min = models.IntegerField(verbose_name='Зарплата от')
    salary_max = models.IntegerField(verbose_name='Зарплата до')
    published_at = models.DateField(null=True, default=date.today)


class Application(models.Model):
    written_username = models.CharField(max_length=128, verbose_name='Ваше имя')
    written_phone = PhoneNumberField(null=False, blank=False, unique=False, verbose_name='Ваш телефон')
    written_cover_letter = models.TextField(verbose_name='Сопроводительное письмо')
    vacancy = models.ForeignKey(Vacancy, on_delete=models.CASCADE, related_name='applications')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='applications')

apps/vacancies/forms.py
from string import Template

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms
from django.forms import ModelForm, Textarea
from django.utils.safestring import mark_safe

from apps.vacancies.models import Application, Company, Vacancy
from vacavaca.settings import MEDIA_URL


class ApplicationForm(ModelForm):
    class Meta:
        model = Application
        fields = ['written_username', 'written_phone', 'written_cover_letter']
        widgets = {
            'written_cover_letter': Textarea(attrs={'rows': 8, }),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Записаться на собеседование'))


class PictureWidget(forms.widgets.Widget):
    def render(self, name, value, attrs=None, **kwargs):
        html = Template("""<img style="max-width: 120px;height: auto;" src="$media$link"/>""")
        return mark_safe(html.substitute(media=MEDIA_URL, link=value))


class CompanyForm(ModelForm):
    class Meta:
        model = Company
        fields = ['name', 'employee_count', 'logo', 'location', 'description']
        widgets = {
            'description': Textarea(attrs={'rows': 8, }),
            'logo': PictureWidget(),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Сохранить', css_class='btn-info'))


class VacancyForm(ModelForm):
    class Meta:
        model = Vacancy
        fields = ['title', 'specialty', 'skills', 'description', 'salary_min', 'salary_max']
        widgets = {
            'description': Textarea(attrs={'rows': 16, }),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Сохранить', css_class='btn-info'))

apps/vacancies/views/mycompany.py
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView, UpdateView

from apps.vacancies.forms import CompanyForm
from apps.vacancies.models import Company


class MyCompanyLetsStart(TemplateView):
    template_name = 'company-lets-start.html'


class MyCompanyBaseEditView(SuccessMessageMixin):
    model = Company
    template_name = 'company-edit.html'
    form_class = CompanyForm
    success_url = reverse_lazy('vacancies:my_company')


class MyCompanyCreateView(MyCompanyBaseEditView, CreateView):
    success_message = 'Компания создана успешно'

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class MyCompanyEditView(MyCompanyBaseEditView, UpdateView):
    success_message = 'Информация о компании обновлена успешно'

    def get_object(self, queryset=None):
        return self.request.user.company

apps/vacancies/views/myvacanciesview.py
from datetime import date

from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, ListView

from apps.vacancies.forms import VacancyForm
from apps.vacancies.models import Vacancy


class MyVacanciesView(ListView):
    template_name = 'vacancy-list.html'
    model = Vacancy

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['vacancies'] = Vacancy.objects.filter(company=self.request.user.company)
        return context


class MyVacancyBaseEditView(SuccessMessageMixin):
    model = Vacancy
    template_name = 'vacancy-edit.html'
    form_class = VacancyForm


class MyVacancyCreateView(MyVacancyBaseEditView, CreateView):
    success_message = 'Вакансия создана успешно'

    def get_success_url(self):
        return reverse_lazy('vacancies:my_vacancy_edit', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        form.instance.company = self.request.user.company
        form.instance.published_at = date.today()
        return super().form_valid(form)


class MyVacancyEditView(MyVacancyBaseEditView, UpdateView):
    success_message = 'Вакансия обновлена успешно'

    def get_success_url(self):
        return reverse_lazy('vacancies:my_vacancy_edit', kwargs={'pk': self.object.pk})

    def get_object(self, queryset=None):
        return get_object_or_404(Vacancy, pk=self.kwargs['pk'])

apps/vacancies/views/public.py
import logging

from django.http import HttpResponseNotFound, HttpResponse, HttpResponseForbidden
from django.db.models import Count, Prefetch
from django.shortcuts import redirect
from django.views.generic import TemplateView, DetailView

from apps.vacancies.forms import ApplicationForm
from apps.vacancies.models import Specialty, Company, Vacancy

TITLE_ALL_VACANCIES = "Все вакансии"


class IndexView(TemplateView):
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['specialities_with_number'] = Specialty.objects.annotate(vacancy_number=Count('vacancies'))
        context['companies_with_number'] = Company.objects.annotate(vacancy_number=Count('vacancies'))
        return context


class VacanciesView(TemplateView):
    template_name = "vacancies.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = TITLE_ALL_VACANCIES
        context['vacancies'] = Vacancy.objects.all()
        return context


class VacanciesBySpecialtyView(DetailView):
    template_name = "vacancies.html"
    model = Specialty
    slug_field = 'code'
    slug_url_kwarg = 'specialty'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.object.title
        context['vacancies'] = Vacancy.objects.filter(specialty=self.object)
        return context


class CompanyView(DetailView):
    template_name = 'company.html'
    context_object_name = 'company'
    queryset = Company.objects.prefetch_related(
        Prefetch('vacancies', queryset=Vacancy.objects.select_related('company', 'specialty'))
    )


class VacancyView(DetailView):
    template_name = 'vacancy.html'
    model = Vacancy
    context_object_name = 'vacancy'
    form_class = ApplicationForm
    queryset = Vacancy.objects.select_related('company')
    object = None

    def get_context_data(self, form=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = form or self.form_class()
        return context

    def post(self, request, pk):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        form = self.form_class(request.POST)
        if form.is_valid():
            application = form.save(commit=False)
            application.user = request.user
            application.vacancy_id = pk
            application.save()
            return redirect('/vacancies/appsuccess')
        self.object = self.get_object()
        return self.render_to_response(self.get_context_data(form=form))


class ApplicationSuccessView(TemplateView):
    template_name = 'app-success.html'


def custom_handler404(request, exception):
    logging.warning(f'Non-existent tour was requested {exception}')
    return HttpResponseNotFound('Кажется такая страница не существует :(')


def custom_handler500(request):
    return HttpResponse('Что-то не так. \nСпециально обученный человек отправлен разобраться.', status=500)

vacancies/views.py
import logging

from django.http import HttpResponseNotFound, HttpResponse
from django.db.models import Count, Prefetch
from django.views.generic import TemplateView, DetailView

from vacancies.models import Specialty, Company, Vacancy

TITLE_ALL_VACANCIES = "Все вакансии"


class IndexView(TemplateView):
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['specialities_with_number'] = Specialty.objects.annotate(vacancy_number=Count('vacancies'))
        context['companies_with_number'] = Company.objects.annotate(vacancy_number=Count('vacancies'))
        return context


class VacanciesView(TemplateView):
    template_name = "vacancies.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = TITLE_ALL_VACANCIES
        context['vacancies'] = Vacancy.objects.all()
        return context


class VacanciesBySpecialtyView(DetailView):
    template_name = "vacancies.html"
    model = Specialty
    slug_field = 'code'
    slug_url_kwarg = 'specialty'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.object.title
        context['vacancies'] = Vacancy.objects.filter(specialty=self.object)
        return context


class CompanyView(DetailView):
    template_name = 'company.html'
    context_object_name = 'company'
    queryset = Company.objects.prefetch_related(
        Prefetch('vacancies', queryset=Vacancy.objects.select_related('company', 'specialty'))
    )


class VacancyView(DetailView):
    template_name = 'vacancy.html'
    model = Vacancy
    context_object_name = 'vacancy'
    queryset = Vacancy.objects.select_related('company')


def custom_handler404(request, exception):
    logging.warning(f'Non-existent tour was requested {exception}')
    return HttpResponseNotFound('Кажется такая страница не существует :(')


def custom_handler500(request):
    return HttpResponse('Что-то не так. \nСпециально обученный человек отправлен разобраться.', status=500)

apps/vacancies/templates/base.html
<!DOCTYPE html>
<html lang="ru">

<head>
  <meta charset="UTF-8">
  <title>{{ title }}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
  <header class="container mt-3">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand mr-4" href="{% url 'vacancies:index' %}">Джуманджи</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
        <ul class="navbar-nav col-10">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'vacancies:vacancies' %}">Вакансии</a>
          </li>

        </ul>
        <ul class="navbar-nav col-2 justify-content-end">
          <li class="nav-item active">
              {% if user.is_authenticated %}
                  <div class="btn-group">
                    <button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ user.first_name }} {{ user.last_name }}
                    </button>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a class="dropdown-item" href="#">Профиль</a>
                        <a class="dropdown-item" href="#">Резюме</a>
                        {% if user.company %}
                            <a class="dropdown-item" href="{% url 'vacancies:my_company' %}">Компания</a>
                        {% else %}
                            <a class="dropdown-item" href="{% url 'vacancies:my_company_lets_start' %}">Компания</a>
                        {% endif %}
                        <a class="dropdown-item" href="{% url 'accounts:logout' %}">Выйти</a>
                    </div>
                  </div>
              {% else %}
                  <a href="{% url 'accounts:login' %} " class="nav-link font-weight-bold">Вход</a>
              {% endif %}
          </li>
        </ul>
      </div>
    </nav>
  </header>
  {% block container %}
  {% endblock %}
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

apps/vacancies/templates/company-edit.html
{% extends 'base.html' %}
{% block container %}
  <style>
    body {
      background-color: #F6F2E6;
    }
  </style>

  <main class="container mt-3 pb-5">
    <div class="row mt-5">
      <div class="col-12 col-lg-4">
        <aside class="pt-3 pb-4 px-4 mb-5 card">
          <h1 class="h4 pt-2 pb-2">Моя компания</h1>
          <div class="nav flex-column nav-pills">
            <a class="nav-link active" href="{% url 'vacancies:my_company' %}">1. Информация о&nbsp;компании</a>
            <a class="nav-link" href="{% url 'vacancies:my_vacancies' %}">2. Вакансии</a>
          </div>
        </aside>
      </div>
      <div class="col-12 col-lg-8">
        <div class="card">
          <div class="card-body px-4 pb-4">
            <!-- Tab -->
           <h2 class="h4 pt-2 pb-3">Информация о&nbsp;компании</h2>
              {% if messages %}
                {% for message in messages %}
                  <p class="alert alert-info" role="alert">
                    {{ message }}
                  </p>
                {% endfor %}
              {% endif %}
              {% load crispy_forms_tags %}
{#              {% crispy form%}#}
              <form  method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                <div class="row">
                  <div class="col-12 col-md-6">
                    <div class="form-group pb-2">
                        {{ form.name|as_crispy_field }}
                    </div>
                  </div>
                  <div class="col-12 col-md-6">
                    <div class="form-group">
                      <div class="row align-items-center">
                        <div class="col-6">
                            {{ form.logo }}
                        </div>
                        <div class="col-6" style="position: relative;">
                          <div class="input-group-prepend" style="position: absolute; top: 0;right: 15px;">
                            <button type="submit" class="btn btn-info px-4">Загрузить</button>
                          </div>
                          <div class="custom-file" style="">
                            <input type="file" class="custom-file-input" id="inputGroupFile01">
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-12 col-md-6">
                    <div class="form-group pb-2">
                        {{ form.employee_count|as_crispy_field }}
                    </div>
                  </div>
                  <div class="col-12 col-md-6">
                    <div class="form-group pb-2">
                        {{ form.location|as_crispy_field }}
                    </div>
                  </div>
                </div>
                <div class="form-group pb-2">
                    {{ form.description|as_crispy_field }}
                </div>
                <div class="form-group">
                    <input type="submit" name="submit" value="Сохранить" class="btn btn-primary btn-info" id="submit-id-submit">
                </div>
              </form>
            <!-- END Tab -->
          </div>
        </div>
      </div>
    </div>
  </main>

{% endblock %}

apps/vacancies/templates/company-lets-start.html
{% extends 'base.html' %}
{% block container %}
  <style>
    body {
      background-color: #F6F2E6;
    }
  </style>

  <main class="container mt-3 pb-5">
    <section class="col-12 col-lg-6 offset-lg-3 mt-5 card">
      <div class="card-body px-3 pb-4">
        <h1 class="h4 pt-2">Моя компания</h1>
        <p class="mt-2">Пока мы думаем, что вы – частное лицо. Хотите создать карточку компании, разместить информаию и вакансии?</p>
        <a href="{% url 'vacancies:my_company_create' %}" class="btn btn-info mb-2">Создать карточку компании</a>
      </div>
    </section>
  </main>

{% endblock %}

apps/vacancies/templates/company.html
{% extends 'base.html' %}
{% block container %}
  <main class="container mt-3">
    <div class="navbar mt-5">
      <p><a href="{{ request.META.HTTP_REFERER }}">Назад</a></p>
    </div>
    <section>
      <div class="text-center">
        <img src="{{ company.logo.url }}" width="130" height="80" alt="">
      </div>
      <h1 class="h1 text-center mx-auto mt-0 pt-1" style="font-size: 70px;"><strong>{{ company.name }}</strong></h1>
      <p class="text-center pt-1">Компания, {{ company.location }}, {{ company.vacancies.count}} вакансий</p>
      <div class="row mt-5">
        <div class="col-12 col-lg-8 offset-lg-2 m-auto">
        {% for vacancy in company.vacancies.all %}
          <div class="card mb-4">
            <div class="card-body px-4">
              <div class="row">
                <div class="col-12 col-md-8 col-lg-9">
                  <h2 class="h2 pb-2">
                    <a href="{% url 'vacancies:vacancy' vacancy.id %}" class="text-dark">{{ vacancy.title }}</a>
                  </h2>
                  <p class="mb-2">{{ vacancy.skills }}</p>
                  <p>От {{ vacancy.salary_min }} до {{ vacancy.salary_max }} руб.</p>
                  <p class="text-muted pt-1">{{ vacancy.published_at|date:"d E" }}</p>
                </div>
                <div class="col-12 col-md-4 col-lg-3 d-flex align-items-end">
                    <a href="{% url 'vacancies:vacancy' vacancy.id %}"><img src="{{ company.logo.url }}" width="130" height="80" alt=""></a>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
        </div>
      </div>
    </section>
  </main>
{% endblock %}

apps/vacancies/templates/index.html
{% extends 'base.html' %}
{% block container %}
  <main class="container mt-3">
    <section>
      <h1 class="h1 text-center mx-auto mt-4 py-5"><strong>Вакансии для <br>Junior-разработчиков</strong></h1>
      <div class="row">
        <div class="col-12 col-md-8 col-lg-6 offset-lg-3 offset-md-2">
          <form class="form-inline mb-3" enctype="multipart/form-data">
            <div class="form-group col-8 col-md-10 pl-0">
              <input class="form-control w-100" type="search" placeholder="Найти работу или стажировку" aria-label="Найти работу или стажировку">
            </div>
            <div class="form-group col-4 col-md-2 pl-0">
              <button class="btn btn-primary w-100" type="submit">Найти</button>
            </div>
          </form>
          <p>Например: 
            <a href="#" class="text-dark border-bottom border-dark m-1 text-decoration-none">Python</a> 
            <a href="#" class="text-dark border-bottom border-dark m-1 text-decoration-none">Flask</a> 
            <a href="#" class="text-dark border-bottom border-dark m-1 text-decoration-none">Django</a> 
            <a href="#" class="text-dark border-bottom border-dark m-1 text-decoration-none">Парсинг</a> 
            <a href="#" class="text-dark border-bottom border-dark m-1 text-decoration-none">ML</a> 

          </p>
        </div>
      </div>
    </section>

    <section class="mt-5 pt-3">
      <h2 class="h2 font-weight-normal text-center mb-5">Вакансии по рубрикам</h2>
      <div class="row mb-0">
      {% for speciality in specialities_with_number %}
        <div class="col-6 col-md-6 col-lg-3">
          <div class="card pt-4 text-center mb-4">
            <img class="mx-auto d-block" src="{{ speciality.picture.url }}" width="80" height="80" alt="">
            <div class="card-body">
              <p class="card-text mb-2">{{ speciality.title }}</p>
              <p class="card-text"><a href="{% url 'vacancies:vacancies_by_specialty' speciality.code %}">{{ speciality.vacancy_number }} вакансий</a></p>
            </div>
          </div>
        </div>
      {% endfor %}
      </div>
    </section>

    <section class="my-5 pt-3">
      <h2 class="h2 font-weight-normal text-center mb-5">Нам доверяют лучшие компании</h2>
      <div class="row mb-0">
      {% for company in companies_with_number %}
        <div class="col-6 col-md-6 col-lg-3">
          <div class="card pt-4 text-center mb-4">
            <a href="{% url 'vacancies:company' company.id %}" style="max-width: 150px;" class="mx-auto d-block">
              <img class="mx-auto d-block mw-100" src="{{ company.logo.url }}" alt="">
            </a>
            <div class="card-body">
              <p class="card-text"><a href="{% url 'vacancies:company' company.id %}">{{ company.vacancy_number }} вакансий</a></p>
            </div>
          </div>
        </div>
      {% endfor %}
      </div>
    </section>
  </main>
{% endblock %}

apps/vacancies/templates/vacancy-list.html
{% extends 'base.html' %}
{% block container %}
  <style>
    body {
      background-color: #F6F2E6;
    }
  </style>

  <main class="container mt-3 pb-5">
    <div class="row mt-5">
      <div class="col-12 col-lg-4">
        <aside class="pt-3 pb-4 px-4 mb-5 card">
          <h1 class="h4 pt-2 pb-2">Моя компания</h1>
          <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
            <a class="nav-link" href="{% url 'vacancies:my_company' %}">1. Информация о&nbsp;компании</a>
            <a class="nav-link active" href="{% url 'vacancies:my_vacancies' %}">2. Вакансии</a>
          </div>
        </aside>
      </div>
      <div class="col-12 col-lg-8">
        <div class="card">
          <div class="card-body px-4 pb-4">
            <section class="tab-pane fade show active">
              <h2 class="h4 pt-2 pb-3">Вакансии</h2>
              <!-- vacancy state 1 -->
              {% if not vacancies %}
                  <p class="alert alert-info" role="alert">У вас пока нет вакансий, но вы можете создать первую!</p>
              {% else %}
              {% for vacancy in vacancies %}
              <div class="card mt-3">
                <div class="card-body px-4">
                  <div class="row align-items-center">
                    <div class="col-6 col-lg-8">
                      <a href="{% url 'vacancies:my_vacancy_edit' vacancy.pk %}" class="mb-1 text-dark">{{ vacancy.title }}</a>
                      <p class="mb-1">
                        <span class="mr-4">{{ vacancy.salary_min }} - {{ vacancy.salary_max }}</span>
                          <a href="{% url 'vacancies:my_vacancy_edit' vacancy.pk %}#applications" class="text-info">{{ vacancy.applications.count }} отклика</a>
                      </p>
                    </div>
                    <div class="col-6 col-lg-4 text-right">
                      <a href="{% url 'vacancies:my_vacancy_edit' vacancy.pk %}" class="btn btn-outline-info">Изменить</a>
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}
              {% endif %}
              <!-- END vacancy state 1 -->
            <a class="btn btn-info mt-3" href="{% url 'vacancies:my_vacancy_create' %}" role="button">Добавить вакансию</a>
            </section>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}